### ISSUE TITLE
Syntax highlighting for Examples

### ISSUE THREAD

**Issue by bodenr** [mattmcmanus/dox-foundation#10]
It would be great if dox-foundation supported syntax highlighting for 'Examples' generated by dox... More details below.

Using dox, you can provide examples:

``` javascsript
/**
 * Escape the given `html`.
 *
 * Examples:
 *
 *     utils.escape('<script></script>')
 *     // => '&lt;script&gt;&lt;/script&gt;'
 *
 * @param {String} html string to be escaped
 * @return {String} escaped html
 * @api public
 */
```

In the HTML code produced, the 'Examples' end up in a code element:

```
<pre>
    <code>
      // Example code here
      // ...
    </code>
</pre>
```

However this element is not syntax highlighted as per dox-foundation... It would great if the examples where highlighted in addition to the actual implementation.

**Comment by mattmcmanus** [comment]
Sorry for the delay! I haven't had a chance to focus on the project for a while. 

I like this idea a lot. I've got an idea for how I will implement it but I'm not sure how quick I can get to it. Feel free to make a pull request!

**Comment by mattmcmanus** [comment]
I just pushed 0.4.0 which adds support for syntax highlighting for examples. Let me know what you think!
