### ISSUE TITLE
Floating side nav support

### ISSUE THREAD

**Issue by bodenr** [mattmcmanus/dox-foundation#11]
IMHO - the HTML generated from dox-foundation would be more user friendly if the nav list (function list side-nav) was floating (i.e. fixed). For example if I've generated a fairly lengthy document and am view it, I have to scroll up (or search) if I want to locate a different function. I think it would make for a better experience if the side nav floated down with the page scroll.

**Comment by mattmcmanus** [comment]
Sorry for the delay in getting back to you. I haven't had much time recently to focus on the project.

I agree with you and I've played around with it a bit but didn't find a setup I liked. I have a couple ideas I'm throwing around for the layout that I will hopefully get to soon.

**Comment by mattmcmanus** [comment]
I just pushed 0.4.0 which adds some floating nav support. I'm sure it will need some more work but let me know what you think!
