### ISSUE TITLE
Twistie for show/hide code & example elements

### ISSUE THREAD

**Issue by bodenr** [mattmcmanus/dox-foundation#12]
It would be great if dox-foundation supported a twistie which would allow the user to show or hide the actual function code and examples.

For example, each of the 

```
<pre>
  <code>
...
  </code>
</pre>
```

blocks which contains the actual source code and example code could have a clickable text heading to show/hide the respective block of code. 

If this enhancement was implemented IMO it would make sense to initially have each of the blocks hidden, so the page was compressed and easy to navigate as with sizable pages. The user could then click the 'show code' or 'show example' to expand the respective section and view the source.

**Comment by mattmcmanus** [comment]
Another request I completely agree with. I'm planning on adding tabs for the doc block and then the source.

**Comment by wactbprot** [comment]
+1
Do you plan to use a "ui library" or write it by yourself?

**Comment by mattmcmanus** [comment]
As much as possible I'm planning on sticking to the out of the box Zurb Foundation experience. Where I need to tweak things I will.

**Comment by mattmcmanus** [comment]
Hey Everyone, 

I know its been a while....

But I just pushed `v.0.5.0` which has support for this. Please give feedback!
