### ISSUE TITLE
Request: Add option for full TOC

### ISSUE THREAD

**Issue by phun-ky** [mattmcmanus/dox-foundation#13]
With that I mean:

Make an option / set default the possibility to have a link meny on the generated html left hand side with links to files that are doxxed/methods. Currently, it seems that only the variables starting with "_" ( like `_service` is displayed in the generated documentation file.

**Comment by mattmcmanus** [comment]
Hey @phun-ky, I'm not sure I follow what you mean. Do you have an example?

Right now, the method list is determined by checking if dox has marked it to ignore or as private, You can see the line here: https://github.com/punkave/dox-foundation/blob/master/lib/dox-foundation.js#L36

**Comment by phun-ky** [comment]
The issue could be that all my JS that I'm testing against is wrapped liked this:

``` javascript
$B.extend({
  init: function(setup){
    var test = "wew";
  }
});
```

Will provide html example and some more code examples on monday

**Comment by phun-ky** [comment]
Would you mind if I could send the generated api.html to you in a PM?

**Comment by mattmcmanus** [comment]
Hey, Is this still an issue? Feel free to send me whatever you need. mcmanus   at punkave.com

**Comment by phun-ky** [comment]
Kinda forgot about this, will check the status and get back to you

**Comment by mattmcmanus** [comment]
Thanks @phun-ky

**Comment by mattmcmanus** [comment]
Feel free to reopen this if you want! I'm closing it for now.
