### ISSUE TITLE
Request: Add support for custom tags

### ISSUE THREAD

**Issue by phun-ky** [mattmcmanus/dox-foundation#14]
I currently use a more phpDoc -style when I am documenting inline code , and also use my own custom tags:

``` javascript
/**
 * Title
 *
 * Description
 * 
 * @file (what's the files name?)
 * @author (who's the author)
 * @calls (what methods do this method call?)
 * @source (where is the data coming from? )
 */
```

**Comment by mattmcmanus** [comment]
That parsing of the documentation is completely done by [visionmedia/dox](/visionmedia/dox). I simply take whatever it gives me and put it in the html. You can see the code here: https://github.com/punkave/dox-foundation/blob/master/views/template.jade#L68

**Comment by phun-ky** [comment]
WIll do a bit more research and bump this issue to visionmedia/dox if I come up empty
