### ISSUE TITLE
support for folders

### ISSUE THREAD

**Issue by sdepold** [mattmcmanus/dox-foundation#2]
nice project! is there any way to parse a whole folder ?

**Comment by sdepold** [comment]
will add that on my own :)

**Comment by mattmcmanus** [comment]
Thanks!

This is definitely the next thing I wanted to add. I have a couple thoughts on it and I'd be happy to hear your own. Right now, you can do a whole folder with the [grunt-dox](/punkave/grunt-dox) plugin. It doesn't do anything special to the output so it looks like one giant list of functions but it's a first step.

To get this to work straight up in dox-foundation, it would take some re-architecting. Right now the whole thing works over `stdin`. I was thinking about adding an option where you could put a standard file glob pattern, like in grunt, and it would still dump to `stdout`

```
dox-foundation --dir="lib/**/*.js" > api.html
```

And the only change in the output would be grouping the sidenav by page? I'm not sure what would be the best output.

**Comment by sdepold** [comment]
added in #5
