### ISSUE TITLE
Generated menu is too long when you generated a lot of files

### ISSUE THREAD

**Issue by phun-ky** [mattmcmanus/dox-foundation#27]
When generating docs for huge number of files, the left side menu is spanning below the viewport, this is especially irritating when the left side menu is `position:fixed`

**Comment by mattmcmanus** [comment]
I added the `position:fixed` code for pages where the left menu may be short and the documentation is really long. I took that approach with the general assumption that if your list is really long on the left, it's probably a good sign that it's time to start tearing off some code into separate modules. 

Do you have an example library that I can test against?

**Comment by phun-ky** [comment]
Hm, I agree that having to many files could clutter up both code and generated documentation. The issue would fall under a "best practice" fix(clearly state in console.log that user is "breaking best practice, please modularize your code" :P ).

But I really think that creating a menu that works regardless of the number of files is still important.

(To reproduce this, just copy a bunch of files and paste again and again, that's what I did)

**Comment by jeremyckahn** [comment]
+1 a fix for this.  The reason I use dox-foundation (and I love it, by the way) is because I can centralize all of my API docs into a single page.  Indeed this can make for a long page, but I really like the simplicity of having everything in one place.  Numerous JavaScript libraries take this approach (Backbone, Underscore, Zepto) and it works quite well.

**Comment by mattmcmanus** [comment]
I'm convinced. So do we agree that simply removing the position:fixed is enough to make this work?

**Comment by jeremyckahn** [comment]
Yep, I just put together a quick-and-dirty Pull Request.  Feel free to go with something more elegant, but it does the trick.

**Comment by mattmcmanus** [comment]
Alrighty. 0.4.7 is out with this update.

**Comment by jeremyckahn** [comment]
Awesome, I like your approach much more.  Thanks for fixing!
