### ISSUE TITLE
Multiple files with same name in different subdirs all are active

### ISSUE THREAD

**Issue by damienklinnert** [mattmcmanus/dox-foundation#31]
When there are multiple files with the same name, but in different subdirectories, all are rendered active. See attached image for example.
![Bildschirmfoto 2013-02-03 um 10 30 58](https://f.cloud.github.com/assets/1471561/121699/8b01cf86-6de4-11e2-8554-a14958e3786a.png)

**Comment by mattmcmanus** [comment]
Good catch. I hadn't come across that yet. I've got a lot of plans to
improve the navigation so ill make sure to fix this when I tackle that.

On Sunday, February 3, 2013, damienklinnert wrote:

> When there are multiple files with the same name, but in different
> subdirectories, all are rendered active. See attached image for example.
> [image: Bildschirmfoto 2013-02-03 um 10 30 58]https://f.cloud.github.com/assets/1471561/121699/8b01cf86-6de4-11e2-8554-a14958e3786a.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/punkave/dox-foundation/issues/31.

## 
- Matt McManus

**Comment by mattmcmanus** [comment]
Hey @damienklinnert, I just pushed a major new version which I think will have taken care of this. Can you test out `v0.5.0` for me?
