### ISSUE TITLE
Omit function source

### ISSUE THREAD

**Issue by terinjokes** [mattmcmanus/dox-foundation#39]
It would be nice if we could use dox-foundataion to build a 'public' API of a private codebase, that is without including the source code.

**Comment by mattmcmanus** [comment]
Hey @terinjokes, sorry for the radio silence!

I like this idea. I've been planning on implementing a tabbed interface which would hide the source by default and allow you to toggle it on. 

Maybe what you've recommended could be implemented with a simple `--no-source-code` flag? I'd love a pull request if you're able

**Comment by mattmcmanus** [comment]
Hey @terinjokes, I was going through the queue here and I implemented this in 0.5. Let me know what you think!
