### ISSUE TITLE
Hidden functions are shown for non-selected files in sidebar nav

### ISSUE THREAD

**Issue by jeremyckahn** [mattmcmanus/dox-foundation#41]
In the projects I use dox-foundation for, I tend to have many files with hidden private functions in each.  To prevent private methods from being rendered in the docs, I use the `/*!*/` convention in the comment header.  As of version 0.5.0, there is an issue with displaying hidden methods' names when expanding the API preview of a non-selected file.  To reproduce, look at a project with multiple files and hidden functions throughout.  I have a sample currently available [here](http://files.jeremyckahn.com/rekapi_dox_bug/dist/doc/src/rekapi.core.js.html#Kapi).  Look at any function's documentation on the first page, and expand another page with hidden functions in the navigation (but do not actually click on a function name to follow the link).  From here you can see functions that should be hidden.  Clicking on any of the function names will follow the link, and from there the hidden functions will actually be hidden, as expected.

Hopefully that makes sense.  I'm happy to clarify if it doesn't.

**[Here are some screenshots](https://drive.google.com/folderview?id=0B_fLjx3rDDelc0hsVzlkbWNoOXc&usp=sharing).**

Thanks!

**Comment by mattmcmanus** [comment]
Most undesirable! I'll take a look at what's going on.

**Comment by mattmcmanus** [comment]
v0.5.2 is out with the fix. It was a very small thing that's been broken for a while but didn't show up until the new template

**Comment by jeremyckahn** [comment]
Awesome, thanks for the fix!  I'm glad it was something simple.
