### ISSUE TITLE
function links with ../../

### ISSUE THREAD

**Issue by wactbprot** [mattmcmanus/dox-foundation#42]
I just installed the latest version 0.5.2 and realized that the links in the sidbar go two levels above the point where `index.html` lives. 

Example: the index.html url is:

```
   http://localhost:5984/vaclab_db/_design/yamp/src_doc/index.html
```

the e.g. the first function (yamp_worker) in the sidebar links to:

```
  http://localhost:5984/vaclab_db/src_doc/yamp.worker.js.html#yamp_worker
```

but has to be:

```
  http://localhost:5984/vaclab_db/_design/yamp/src_doc/yamp.worker.js.html#yamp_worker
```

It looks for me that there is a uncorrect  `../../` somewhere.

thank you & regards

**Comment by wactbprot** [comment]
got it! 
couchdb tools like couchapp or erica have a folder called `_attachments`. you have this folder in the local path but not in the url. In my case the two `../` came 1. from `--target=_attachments/src_doc` and 2. from `--source=_attachments/vl`. 

The solution is a simple **cd**:

`cd _attachment` followed by `--target=src_doc --source=vl`

**Comment by mattmcmanus** [comment]
Interesting! It should be smart enough to know that though. That link generating code has always felt a bit fragile to me.

**Comment by wactbprot** [comment]
The point is that for the two `_attachments` folder (targetPath/srcPath/file.js) two `../` are added which don't have an  equivalent on the server. 

Thank you for your attention!
