### ISSUE TITLE
doctype html + css not working

### ISSUE THREAD

**Issue by acornejo** [mattmcmanus/dox-foundation#48]
A freshly installed copy of dox-foundation (from npm) doesn't work. I suspect this is due to a new version of jade. Error is:

``` bash
dox-foundation < myfile.js > myfile.html                                                                                                                                 

/usr/local/lib/node_modules/dox-foundation/node_modules/jade/lib/runtime.js:200
  throw err;
        ^
Error: /usr/local/lib/node_modules/dox-foundation/views/template.jade:73
    71| 
    72|     include ./_footer.jade
  > 73| 

`doctype 5` is deprecated, you must now use `doctype html`
```

I edited the offending file and corrected the doctype issue. However the produced html still doesn't work.

**Comment by acornejo** [comment]
I've confirmed the problem is due to a newer version of jade being used. I am creating a pull request to fix the issue.

**Comment by mattmcmanus** [comment]
Alrighty! `0.5.5` is out and working. Thanks for the help!
