### ISSUE TITLE
subTitle is not defined

### ISSUE THREAD

**Issue by wactbprot** [mattmcmanus/dox-foundation#6]
I got the  error message in the suject on a fresh installed system:
dox-foundation < dox-test.js 
wherby dox-test.js is 

```
 /*
  * valStat
  * @param x 
  * @return res 
  */
 vlStat = function(x){

     if (x && x.length > 2){
     ...
     }
 };
 exports.vlStat = vlStat;
```

I have the version (installed over npm) 0.0.1

**Comment by mattmcmanus** [comment]
Could you try updating? It should be at version 0.3.1.

**Comment by wactbprot** [comment]
this is what I have (a npm update don't work):

```
 dox-foundation@0.3.1 /usr/lib/node_modules/dox-foundation
 ├── commander@0.5.2
 ├── underscore@1.4.2
 ├── dox@0.3.2 (commander@0.6.1, github-flavored-markdown@1.0.1)
 ├── jade@0.27.6 (commander@0.6.1, mkdirp@0.3.4)
 └── walk@2.2.1 (forEachAsync@2.2.0)
 # dox-foundation --version
 0.0.1
```

So there is a version mismatch.
However, everything works fine if I use the HEAD files of dox-foundation repo.

**Comment by dcardosods** [comment]
I had the same error, using from npm and github repo

**Comment by cleonello** [comment]
Same error here.  Fresh install via npm.  Also have the same version mismatch as wactbprot.

**Comment by mattmcmanus** [comment]
Thanks for the reports everyone. I'll try to take a look at this today.

**Comment by mattmcmanus** [comment]
Version 0.3.2 is now up on npm. Fixes the version number problem and the subtitle error

**Comment by wactbprot** [comment]
Hey; I got 0.3.3 over npm (and it works very well)! THX

**Comment by dcardosods** [comment]
works fine now, thanks
