### ISSUE TITLE
spurious number 

### ISSUE THREAD

**Issue by rolfn** [mattmcmanus/dox-foundation#8]
"dox-foundation" produces a spurious number in the upper left corner of the html page. Small example:

<pre>
echo -e '/**\n * @param x\n */\nfunction foo(x){\nreturn x};\n' | \
  dox-foundation > xx.html
</pre>

Before "<!DOCTYPE html>" as the first character in the html code you can see the number "1". It's not a big problem, but...

Greetings from Berlin

Rolf

**Comment by mattmcmanus** [comment]
Thanks for making an issue for this. I've been trying to find out how this is getting in here for a while. Can't quite hunt it down just yet. I'll continue hunting.

**Comment by mattmcmanus** [comment]
Try updating dox. I think that took care of the problem as it's not happening for me anymore.
