### ISSUE TITLE
relative pathes for links

### ISSUE THREAD

**Issue by rolfn** [mattmcmanus/dox-foundation#9]
I have the two directories "foo" and "docs". Inside of "foo" is the file "foo.js". I call

 dox-foundation --source foo --target docs

and get 

  docs/foo.js.html
  docs/index.html

This structure is  working as long as  the directory is not moved or e.g. installed inside a database like "couchdb". The reason is: "dox-foundation" wites absolute (!) pathes to "index.html". This is bad. In the example I see

  "/home/niepra01/tmp/docs/foo.js.html"

as link target instead of 

  "docs/foo.js.html".

Greetings from Berlin

...Rolf

**Comment by mattmcmanus** [comment]
Howdy @rolfn. I just pushed 0.4.0 which I believe should fix this problem and add some other nice features. Sorry for the delay!
